### ISSUE TITLE
Branch Strategies

### ISSUE THREAD

**Issue by aykutbulut** [coin-or/CHiPPS-BLIS#1]
createCandBranchObjects is a virtual function in BcpsBranchStrategy class. BlisBranchStrategy\* classes inherit BcpsBranchStrategy class. Some of them (BlisBranchStrategyBilevel, BlisBranchStrategyMaxInf, BlisBranchStrategyStrong) implement createCandBranchObjects function some of them (BlisBranchStrategyPseudo, BlisBranchStrategyRel) overwrite it. This is confusing.

I think the following is a better design (and what is intended originally). BcpsBranchStrategy::createCandBranchObjects should be pure virtual. All Blis branch strategy classes should implement it.

Aykut

**Comment by tkralphs** [comment]
Hmm, the difference you're referring to seems to be that in, e.g., `BlisBranchStartegyStrong.h`, `createCandBranchObjects` is declared `virtual` and in, e.g., `BlisBranchStrategyRel`, `createCandBranchObjects` is not declared virtual. Is this what you mean by "implemented" versus "overwritten" (overridden)? It would certainly be good to have uniformity, just for code clarity, but it seems these two are equivalent (see [here](https://stackoverflow.com/questions/4895294/c-virtual-keyword-for-functions-in-derived-classes-is-it-necessary)). The virtual keyword is implied in the derived class, whether it is present or not. 

In any case, can you provide a PR to fix this in consistency?

**Comment by aykutbulut** [comment]
Yes that is what I meant. I realized both are equivalent. I added "virtual" in the declarations to emphasize the intent and consistency. I did not make BcpsBranchStrategy::createCandBranchObjects pure, not to break build in other projects.

Fixed in the following commit.
https://github.com/coin-or/CHiPPS-BLIS/commit/3bd03d389aa51eb27fb240b15371a1a7438309d5
